//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerHardware
    {
        public int ComputerHardwareID { get; set; }
        public string ComputerID { get; set; }
        public int HardwareID { get; set; }
        public string AmvalCode { get; set; }
        public string Serial { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Hardware Hardware { get; set; }
    }
}
