//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryComputer
    {
        public string Computer_ID { get; set; }
        public int unit { get; set; }
        public int TypeOfComputer { get; set; }
        public string AmvalCode { get; set; }
        public string Serial { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ComputerName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string unitTitle { get; set; }
    }
}
