//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver
    {
        public int id { get; set; }
        public string ComputerID { get; set; }
        public int UserID { get; set; }
        public string ComputerName { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual User User { get; set; }
    }
}
