//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftwareReportEntities : DbContext
    {
        public SoftwareReportEntities()
            : base("name=SoftwareReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<ComputerHardware> ComputerHardware { get; set; }
        public virtual DbSet<ComputerSoftware> ComputerSoftware { get; set; }
        public virtual DbSet<ComputerType> ComputerType { get; set; }
        public virtual DbSet<Disablement> Disablement { get; set; }
        public virtual DbSet<Hardware> Hardware { get; set; }
        public virtual DbSet<HardwareType> HardwareType { get; set; }
        public virtual DbSet<Input> Input { get; set; }
        public virtual DbSet<InputDetail> InputDetail { get; set; }
        public virtual DbSet<Output> Output { get; set; }
        public virtual DbSet<OutputDetail> OutputDetail { get; set; }
        public virtual DbSet<PeriodicVisits> PeriodicVisits { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<ServiceImage> ServiceImage { get; set; }
        public virtual DbSet<Software> Software { get; set; }
        public virtual DbSet<SubUnit> SubUnit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOFService> TypeOFService { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<Deliver> Deliver { get; set; }
        public virtual DbSet<DeliveryComputer> DeliveryComputer { get; set; }
    }
}
