//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputDetail
    {
        public int InputDetailID { get; set; }
        public int InputID { get; set; }
        public int HardwareID { get; set; }
        public int Tedad { get; set; }
    
        public virtual Hardware Hardware { get; set; }
        public virtual Input Input { get; set; }
    }
}
